### ISSUE TITLE
Licence 

### ISSUE THREAD

**Issue by npettiaux** [cathleruste/HEB-ESI-Java-Labo#23]
Le TD1 à la date d'aujourd'hui a, dans sa version en ligne, comme licence CC-BY dans sa version internationale et aucune mention de licence dans la version papier. 

La clause de partage à l'identique (SA) et la mention belge méritent sans doute un examen, de même que l'ajout à la version pdf destinée à être imprimée.

Le code ci-dessous, provenant du sélectionneur de licence de Creative Commons, peut être intéressant pour la page d'intro de la version web.

<a rel="license" href="http://creativecommons.org/licenses/by-sa/2.0/be/"><img alt="Licence Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/2.0/be/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/InteractiveResource" property="dct:title" rel="dct:type">ESI - Laboratoires de java 1ère</span> de <a xmlns:cc="http://creativecommons.org/ns#" href="http://elearning.esi.heb.be" property="cc:attributionName" rel="cc:attributionURL">Catherine Leruste - Marco Codutti</a> est mis à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by-sa/2.0/be/">licence Creative Commons Paternité - Partage à l&#39;Identique 2.0 Belgique</a>.<br />Basé(e) sur une oeuvre à <a xmlns:dct="http://purl.org/dc/terms/" href="ttps://github.com/cathleruste/HEB-ESI-Java-Labo/" rel="dct:source">github.com</a>.<br />Les autorisations au-delà du champ de cette licence peuvent être obtenues à <a xmlns:cc="http://creativecommons.org/ns#" href="http://www.heb.be/esi" rel="cc:morePermissions">http://www.heb.be/esi</a>.

**Comment by mcodutti** [comment]
Je vais l'ajouter au PDF.

Pour ce qui est de la licence précise, j'avais l'habitude de mettre SA mais Nicolas (l'autre) m'a convaincu que ce n'était pas vraiment une bonne idée. Argument :
- Si quelqu'un modifie le document et a envie de le vendre pourquoi pas ? Il y a toujours mention de l'original gratuit. Les gens n'achèteront que s'il y a une réelle plus-value.

Ton avis m'intéresse...

**Comment by npettiaux** [comment]
Je crois que nous sommes d'accord avec NVS que la bonne licence est BY (citation) SA (partage à l'identique). Donc pas NC (non commercial). Cela permet de effectivement de vendre, par exemple simplement rentrer dans ses frais, ou vendre avec une réelle plus-value comme tu le dis, mais permet aussi aux auteurs et contributeurs originaux (nous ;-) d'avoir accès au contenu adapté, voire aussi de le vendre de notre coté. Cela initie une dynamique vertueuse. 

Ne pas mettre la clause SA permet à d'autre de fermer le document (comme la licence BSD) et donc nous prive de pouvior accéder aux compléments et les redistribuer ou les vendre nous même.

Super pour le pdf, mais pourquoi pas aussi dans le document web ?

**Comment by mcodutti** [comment]
OK pour moi.
Je vais faire ça dans les 2.

Le 28 mai 2012 14:23, Nicolas Pettiaux <
reply@reply.github.com

**Comment by mcodutti** [comment]
On va le fermer quand j'aurai fini de le faire.
Ainsi, ces issues servent aussi de ToDo list

**Comment by npettiaux** [comment]
OK.
