### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by cathleruste** [cathleruste/HEB-ESI-Java-Labo#24]
Revoir les images des tds... Un volontaire ?

**Comment by cathleruste** [comment]
td7 prépa : image : s/t/entiers

**Comment by cathleruste** [comment]
Quelqu'un veut bien s'y coller svp ? (Je peux préciser ici ce que je voulais qu'on refasse au fur et à mesure de ma relecture)

**Comment by mcodutti** [comment]
Je veux bien m'y coller

**Comment by cathleruste** [comment]
Vendu ! 
TD2 : Les permissions : activité : /image/ls-l-permissions.jpg : il y a une flèche qui traine (détail)

**Comment by cathleruste** [comment]
TD6 : Mise en pratique : Rajouter un graphique de l'arborescence pour les approches 3 et 4.

**Comment by mcodutti** [comment]
Vérifier les schéma du TD6

**Comment by cathleruste** [comment]
Vérifié les images. Merci pour le boulot !
