### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by cathleruste** [cathleruste/HEB-ESI-Java-Labo#25]
J'ai oublié de modifier les posNumber des métadata.

**Comment by cathleruste** [comment]
En profiter pour actualiser les acronymes des profs de l'année prochaine.

**Comment by mcodutti** [comment]
Pour les posNumber, pas d'urgence vu que je ne l'utilise pas pour le moment.
Pour les acronymes, attendre d'avoir celui du nouveau prof et je ferai un changement global via un "sed"

**Comment by mcodutti** [comment]
Fait pour les posNumber
