### ISSUE TITLE
gap answer

### ISSUE THREAD

**Issue by mcodutti** [cathleruste/HEB-ESI-Java-Labo#29]
Quand on met des "," dans les answer de gap, il ne considère que ce qui est AVANT la virgule comme solution !
C'est très gênant pour une solution du genre "{{1.1,1.2},{2.1,2.2},{3.1,3.2}}" où la solution affichée n'est que "{{1.1" :S

**Comment by cathleruste** [comment]
Tu t'occupes de faire la modif dont tu m'as parlé ? Du coup, il faudra virer les différentes possibilités de réponse.

**Comment by cathleruste** [comment]
Up 
(cfr PrepaListe : Méthode set)

**Comment by mcodutti** [comment]
C'est pas encore bon en fait. Je continue...

**Comment by mcodutti** [comment]
OK, je pense que c'est bon.
J'ai ajouté l'attribut facultatif "separator" à la balise <gap> pour indiquer un séparateur alternatif.
Ex: <gap answers="set(10, 3)/set(10,3)/set( 10, 3 ) separator="/">set (10, 3)</gap>

J'ai adapté le TDListePrepa en conséquence mais pas le reste.
Je me souviens que ce problème apparait dans un autre TD mais je ne sais plus lequel.

**Comment by cathleruste** [comment]
C'est resté dans Td8Prépa :)

**Comment by mcodutti** [comment]
Est-ce qu'on peut clore cet issue ?

**Comment by cathleruste** [comment]
T'as modifié dans la prépa td8 ? (Moi pas)

**Comment by mcodutti** [comment]
Je ne sais pas.
On ira vérifier une autre fois...
