### ISSUE TITLE
Guillemets à la française

### ISSUE THREAD

**Issue by mcodutti** [cathleruste/HEB-ESI-Java-Labo#30]
Dans la version papier, les guillemets ne sont représentés par 2 apostrophes et pas "à la française" comme c'est normalement prévu par LaTeX. Essayer de modifier le script eLML -> LaTeX pour corriger çà

**Comment by mcodutti** [comment]
Le script actuel change les " en double apostrophe.
-> Enlever cette conversion et le guillemet aura un meilleure rendu.
Ce n'est pas encore un rendu à la française mais je ne vois pas comment distinguer un \og d'un \fg.
Possibilité : mettre à la main dans le .xml les guillements ouvrants ou fermants.

**Comment by cathleruste** [comment]
"Possibilité : mettre à la main dans le .xml les guillements ouvrants ou fermants." :
Vu trop tard mais tu voudrais que je remplace tous les guillemets dans le texte ? - tu peux répondre "non" ;) -

**Comment by pbettens** [comment]
Ouaip ! On peut répondre «non» ;-)

**Comment by mcodutti** [comment]
OK pour moi.

**Comment by cathleruste** [comment]
Merci les loulous ! On peut clôturer alors ?
