### ISSUE TITLE
Tds sous poESI

### ISSUE THREAD

**Issue by cathleruste** [cathleruste/HEB-ESI-Java-Labo#33]
Si on utilise les "flèches" du document, en haut à droite, plutôt que celles du parcours, le parcours n'est pas "comptabilisé".

**Comment by cathleruste** [comment]
Quand on revient en arrière dans le parcours (flèche de gauche), le pourcentage augmente (mais une seule fois) !

**Comment by cathleruste** [comment]
Les métadonnées sont comptabilisées dans le pourcentage et quand on a tout fini, on arrive à un total de 95%

**Comment by mcodutti** [comment]
Je peux facilement les enlever (et je le ferai) mais c'est plus facile en
phase de test;
pas besoin de passer par poÉSI pour passer de page en page.

Le 2 juin 2012 21:57, cathleruste <
reply@reply.github.com

**Comment by cathleruste** [comment]
J'avais bien compris ;) c'est juste une "note pour plus tard". 
Merci!

**Comment by cathleruste** [comment]
Pas sûre d'avoir compris...
mais, de toute façon, il faut garder une version fléchée pour la version sur le réseau.

**Comment by cathleruste** [comment]
TD6BisPrepa : menu en haut de chaque page.

**Comment by mcodutti** [comment]
Mon nouveau script automatise la tâche et crée une version sans menu pour poÉSI et une version avec menu pour la version locale (distri)
