### ISSUE TITLE
style="javawithblanks"

### ISSUE THREAD

**Issue by cathleruste** [cathleruste/HEB-ESI-Java-Labo#34]
Tu peux me dire ce que ça apporte (cfr. TD7BisPrepa ligne 50)  ?

**Comment by mcodutti** [comment]
J'avais des problèmes avec des caractères spéciaux dans un gap (genre <) et
avec ce style là ça passe.
Pas obligatoire sinon :)

**Comment by cathleruste** [comment]
Ok, merci. J'avais espoir que ça marche aussi pour les gap answers mais... non :(
