### ISSUE TITLE
'&' dans title

### ISSUE THREAD

**Issue by cathleruste** [cathleruste/HEB-ESI-Java-Labo#36]
On ne peut pas mettre le symbole '&' dans un title. Une solution ?

**Comment by mcodutti** [comment]
Écrire &amp; à la place ?

2012/7/5 cathleruste <
reply@reply.github.com

**Comment by cathleruste** [comment]
:) (Déjà trop de vacances pour moi ^^ - ou pas assez...)
Merci Marco!
