### ISSUE TITLE
TD2

### ISSUE THREAD

**Issue by mcodutti** [cathleruste/HEB-ESI-Java-Labo#44]
Dans la version papier, le "cat --number" semble n'avoir qu'un seul tiret alors que la version html en a bien deux.
Idem pour "ls --help"

**Comment by cathleruste** [comment]
@mcodutti : tu t'occupes de voir ça dans le .tex ou je m'en charge \* plus tard\* ?

**Comment by mcodutti** [comment]
Si je ne l'ai pas résolu tout de suite, c'est probablement que c'est pas évident mais je vais y re-jeter un oeil.

**Comment by cathleruste** [comment]
Je peux y regarder à l'occasion mais j'ai _quelques priorités_ avant.

**Comment by mcodutti** [comment]
LaTeX interprète '--' comme un tiret moyen (la différence n'est pas très visible) sauf en mode verbatim.
J'ai donc remplacé la conversion LaTeX d'un paragraph en style 'input' de \texttt vers \verb.
Je n'ai pas vérifié que ça ne pose pas de problème ailleurs (mais ça ne devrait pas !)
