### ISSUE TITLE
TD00 1 

### ISSUE THREAD

**Issue by pbettens** [cathleruste/HEB-ESI-Java-Labo#60]
Je relis le PDF

IllegalArgumentException déborde dans la marge
Point 7 et point 12 s/Écivez/Écrivez 
Page suivante, la méthode compareTo déborde aussi ainsi que autreDate

Je n'ai pas vérifié les références dans le syllabus de logique

**Comment by npettiaux** [comment]
- ajouter un point entre 4 et 5, ou compléter le point 4 MAIN pour indiquer d'exécuter la classer MainDate et vérifier qu'elle fonctionne comme attendu. (l'implicite n'est pas compris par bcp d'élèves)
- dans le point 6 pour utiliser la méthode nbJours, ce n'est pas clair si il faut copier et coller le code ou faire un import sans coller (mais alors comment faire puisque la classe n'est pas dans un package). Je mettrais "que vous copierez ici".
- dans le point 9  et les autres MAIN : idem. Indiquer d'exécuter pour voir les résultats (ou l'écrire 1 fois au dessus)

**Comment by cathleruste** [comment]
- dans le point 6 pour utiliser la méthode nbJours, ce n'est pas clair si il faut copier et coller le code ou faire un import sans coller (mais alors comment faire puisque la classe n'est pas dans un package). Je mettrais "que vous copierez ici".

Mais si mais si, elle est dans un package !!!!
- dans le point 9 et les autres MAIN : idem. Indiquer d'exécuter pour voir les résultats (ou l'écrire 1 fois au dessus)

Tu crois que je dois aussi écrire qu'ils doivent compiler avant... ^^ 
Si, en début du deuxième quadri, ils ne savent pas qu'ils doivent exécuter leur méthode main pour voir les résultats, je trouve ça bien malheureux... (mais je veux bien rajouter (en râlant) l'info dans le td si elle semble utile...)

**Comment by pbettens** [comment]
on pourrait intervertir (pour l'exo date) le point qui demande de récrire toString avec celui qui demande d'écrire un test.
