### ISSUE TITLE
pdf

### ISSUE THREAD

**Issue by cathleruste** [cathleruste/HEB-ESI-Java-Labo#62]
TDOO : 
IllegalArgumentException déborde dans la marge
la méthode compareTo déborde aussi ainsi que autreDate

**Comment by mcodutti** [comment]
Le problème est que le code Java est traduit en LaTeX par du verbatim qui ne passe pas à la ligne automatiquement.

Solution 1 : Utiliser le package listings
Remplacer le "\verb" par un truc du genre "\lstinline[language=Java,breaklines=true,basicstyle=\ttfamily]"
Cette commande va couper ENTRE les mots mais pas un mot ce qui ne résoud pas nos problèmes concrets.

Solution 2 : Passer à la ligne mais ce sera plutôt laid en HTML

Solution 3 : Passer à la ligne uniquement en LaTeX.
Je pourrais imaginer d'introduire une écriture du genre `<formatted style="LatexNewline"/>`
qui passerait à la ligne en LaTeX et serait ignorée pour HTML.

**Comment by mcodutti** [comment]
Bon j'ai opté pour la solution 3 qui me parait très bien.
C'est en tout cas OK pour le TD OO.
Je n'ai pas regardé s'il y avait d'autres dépassement de lignes ailleurs.
