### ISSUE TITLE
Modifications des règles pour le mot de passe

### ISSUE THREAD

**Issue by mcodutti** [cathleruste/HEB-ESI-Java-Labo#63]
- Au 2.1 : le mot de passe Windows n'est plus donné par le professeur mais reçu lors de l'inscription.
- Au 2.2 : le mot de passe poÉSI n'est plus le même que celui de Windows. Ils reçoivent un mail à ce sujet sur leur adresse heb.be

**Comment by pbettens** [comment]
… en fait, j'ai modifié mais j'ai pas réussi à compiler …

**Comment by cathleruste** [comment]
Par rapport à _gap_, c'est dans le fichier elml.xsd qui se trouve dans _config
